import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Generated by DartBuilder Logic Engine
class HomeProvider extends ChangeNotifier {

  // --- State Variables ---
  List<dynamic> _userLists = [];

  // --- Getters ---
  List<dynamic> get userLists => _userLists;

  // --- Init ---
  void init(BuildContext context) {
    _userLists = [];
    getData();
    notifyListeners();
  }

  // --- Actions ---

  Future<void> getData() async {
    _userLists = await Supabase.instance.client.from('users').select('*');
    print(_userLists.toString());
    notifyListeners();
  }

  Future<void> addUser() async {
    await Supabase.instance.client.from('users').insert({'user_id': 'google-oauth2|105563299510762116909', 'email': 'winmin.yau@gmail.com', 'name': 'Win Min', 'plan_type': 'free', 'picture': 'https://lh3.googleusercontent.com/a/ACg8ocLsvZrH7OJsxGtYGDepKtRnwgUyVrIOFtfLlD5ERs2xJrH3kw=s96-c'});
    getData();
    notifyListeners();
  }

  // --- Reset ---
  void resetAll() {
    _userLists = [];
    notifyListeners();
  }
}
